
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package TP_Final.compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int distinto = 13;
  public static final int palabraif = 23;
  public static final int palabradecvar = 25;
  public static final int palabrawhile = 30;
  public static final int corcheteC = 20;
  public static final int constString = 34;
  public static final int corcheteA = 19;
  public static final int palabrafloat = 27;
  public static final int coma = 21;
  public static final int igual = 18;
  public static final int palabraint = 28;
  public static final int palabrastring = 29;
  public static final int dividido = 5;
  public static final int palabraprint = 31;
  public static final int menos = 3;
  public static final int palabraenddec = 26;
  public static final int menor = 16;
  public static final int EOF = 0;
  public static final int mas = 2;
  public static final int error = 1;
  public static final int mayor = 17;
  public static final int asignaCTE = 12;
  public static final int palabraelse = 24;
  public static final int menorigual = 14;
  public static final int por = 6;
  public static final int cte = 35;
  public static final int palabrafilter = 32;
  public static final int cteReal = 36;
  public static final int id = 33;
  public static final int guion_bajo = 22;
  public static final int bloqueC = 10;
  public static final int mayorigual = 15;
  public static final int bloqueA = 9;
  public static final int parentesisC = 8;
  public static final int asigna = 11;
  public static final int parentesisA = 7;
  public static final int eol = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "eol",
  "dividido",
  "por",
  "parentesisA",
  "parentesisC",
  "bloqueA",
  "bloqueC",
  "asigna",
  "asignaCTE",
  "distinto",
  "menorigual",
  "mayorigual",
  "menor",
  "mayor",
  "igual",
  "corcheteA",
  "corcheteC",
  "coma",
  "guion_bajo",
  "palabraif",
  "palabraelse",
  "palabradecvar",
  "palabraenddec",
  "palabrafloat",
  "palabraint",
  "palabrastring",
  "palabrawhile",
  "palabraprint",
  "palabrafilter",
  "id",
  "constString",
  "cte",
  "cteReal"
  };
}

